export const POSTGRES_MIGRATIONS = [
  {
    version: 1,
    name: 'initial_durable_schema',
    sql: `
      CREATE TABLE IF NOT EXISTS schema_metadata (key TEXT PRIMARY KEY, value TEXT, updated_at TIMESTAMPTZ);
      CREATE TABLE IF NOT EXISTS incidents (
        id TEXT PRIMARY KEY, type TEXT, location TEXT, lat DOUBLE PRECISION, lng DOUBLE PRECISION,
        time TEXT, status TEXT, severity TEXT, priority TEXT, resolved_at TEXT, acknowledged_at TEXT,
        operator TEXT, notes TEXT, source TEXT, payload TEXT
      );
      CREATE TABLE IF NOT EXISTS audit_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, operator TEXT, action TEXT, entity TEXT,
        result TEXT, correlation_id TEXT, details TEXT, command_id TEXT, idempotency_key TEXT,
        actor_role TEXT, source_instance_id TEXT, leader_instance_id TEXT, timestamp TEXT
      );
      CREATE TABLE IF NOT EXISTS signal_configs (
        node_id TEXT PRIMARY KEY, green_split INTEGER, cycle_time INTEGER, mode TEXT, updated_at TEXT
      );
      CREATE TABLE IF NOT EXISTS device_telemetry (
        device_id TEXT PRIMARY KEY, type TEXT, status TEXT, battery INTEGER, ping_ms INTEGER, fps INTEGER,
        resolution TEXT, green_wave_sync BOOLEAN, updated_at TEXT, payload TEXT
      );
      CREATE INDEX IF NOT EXISTS idx_audit_time ON audit_logs(timestamp DESC);
      CREATE INDEX IF NOT EXISTS idx_audit_corr ON audit_logs(correlation_id);
      CREATE INDEX IF NOT EXISTS idx_audit_command ON audit_logs(command_id);
      CREATE INDEX IF NOT EXISTS idx_audit_idempotency ON audit_logs(idempotency_key);
      CREATE INDEX IF NOT EXISTS idx_incidents_status ON incidents(status);
      CREATE INDEX IF NOT EXISTS idx_incidents_time ON incidents(time DESC);
    `
  },
  {
    version: 2,
    name: 'durable_audit_deduplication',
    sql: `
      CREATE TABLE IF NOT EXISTS audit_deduplication_keys (
        dedupe_key TEXT PRIMARY KEY,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
      INSERT INTO audit_deduplication_keys(dedupe_key)
      SELECT DISTINCT 'corr:' || correlation_id FROM audit_logs WHERE correlation_id IS NOT NULL
      ON CONFLICT(dedupe_key) DO NOTHING;
      INSERT INTO audit_deduplication_keys(dedupe_key)
      SELECT DISTINCT 'idem:' || idempotency_key FROM audit_logs WHERE idempotency_key IS NOT NULL
      ON CONFLICT(dedupe_key) DO NOTHING;
    `
  },
  {
    version: 3,
    name: 'durable_command_receipts',
    sql: `
      CREATE TABLE IF NOT EXISTS command_receipts (
        actor_id TEXT NOT NULL,
        idempotency_key TEXT PRIMARY KEY,
        fingerprint TEXT NOT NULL,
        command_id TEXT NOT NULL,
        correlation_id TEXT NOT NULL,
        action TEXT NOT NULL,
        status TEXT NOT NULL,
        result_json TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        completed_at TIMESTAMPTZ
      );
      CREATE UNIQUE INDEX IF NOT EXISTS idx_command_receipts_command ON command_receipts(command_id);
      CREATE INDEX IF NOT EXISTS idx_command_receipts_created ON command_receipts(created_at DESC);
    `
  },
  {
    version: 4,
    name: 'postgres_leadership_fencing',
    sql: `
      CREATE TABLE IF NOT EXISTS cluster_leadership_fence (
        scope TEXT PRIMARY KEY,
        epoch BIGINT NOT NULL,
        leader_instance_id TEXT NOT NULL,
        lease_expires_at TIMESTAMPTZ NOT NULL,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
      );
      CREATE INDEX IF NOT EXISTS idx_cluster_leadership_fence_expiry ON cluster_leadership_fence(lease_expires_at);
    `
  }
];

export async function runPostgresMigrations(pool) {
  const client = await pool.connect();
  try {
    await client.query('SELECT pg_advisory_lock($1)', [741903122]);
    await client.query(`CREATE TABLE IF NOT EXISTS schema_migrations (
      version INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )`);
    const { rows } = await client.query('SELECT version FROM schema_migrations');
    const applied = new Set(rows.map((row) => Number(row.version)));
    for (const migration of POSTGRES_MIGRATIONS) {
      if (applied.has(migration.version)) continue;
      await client.query('BEGIN');
      try {
        await client.query(migration.sql);
        await client.query('INSERT INTO schema_migrations(version, name) VALUES ($1, $2)', [migration.version, migration.name]);
        await client.query('COMMIT');
      } catch (error) {
        await client.query('ROLLBACK');
        throw error;
      }
    }
  } finally {
    try { await client.query('SELECT pg_advisory_unlock($1)', [741903122]); } catch (_) {}
    client.release();
  }
}
